version: "3.8"

services:
  fastapi-app:
    build: .
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379" # Map host port 6379 to Redis container port 6379
